# Generated by Django 3.0.5 on 2020-04-13 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_device_id', models.UUIDField(default=uuid.UUID('ea40f944-63f6-4e69-bdd7-bf3e5430a4cb'), editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=255)),
                ('current_state', models.CharField(default='off', max_length=255)),
                ('current_value', models.TextField(null=True)),
            ],
        ),
    ]
