# Generated by Django 3.0.5 on 2020-04-19 22:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='channel',
            field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='device',
            name='unique_device_id',
            field=models.UUIDField(default=uuid.UUID('73b950ad-ecc5-4e79-a230-d46bc97c1a2f'), editable=False, unique=True),
        ),
    ]
