# Generated by Django 3.0.5 on 2020-04-20 08:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20200420_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='unique_device_id',
            field=models.UUIDField(default=uuid.UUID('3c2c644e-02c5-4bbc-b2e8-e431dacdc14f'), editable=False, unique=True),
        ),
    ]
