# Generated by Django 3.0.5 on 2020-04-19 22:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_auto_20200419_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_task_id', models.UUIDField(default=uuid.UUID('2eb4dd5b-8aca-4a33-9d26-5886edd6ad1d'), editable=False, unique=True)),
                ('task_todo', models.TextField(default='off')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
            ],
        ),
    ]
