# Generated by Django 3.0.5 on 2020-04-20 08:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200420_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='unique_task_id',
            field=models.UUIDField(default=uuid.UUID('86b9ba0c-d4d4-4255-8723-66209f76e210'), editable=False, unique=True),
        ),
    ]
